name: Windows Build & Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Install Go dependencies
        run: |
          go get .

      - name: Install OpenCV
        run: |
          chdir "$(go env GOPATH)\pkg\mod\gocv.io\x\gocv@v0.42.0"
          mkdir -Force "$(go env GOPATH)\src\gocv.io\x\gocv"
          $env:GOPATH = go env GOPATH
          .\win_build_opencv.cmd

      - name: Verify OpenCV
        run: |
          chdir "$(go env GOPATH)\pkg\mod\gocv.io\x\gocv@v0.42.0"
          $env:PATH = 'C:\opencv\build\install\x64\mingw\bin;' + $env:PATH
          go run cmd\version\main.go

      - name: Build
        run: |
          go build -v ./...

      - name: Test
        run: |
          go test -v ./...

      - uses: actions/upload-artifact@v6
        if: ${{ success() || failure() }}
        with:
          name: artifacts
          if-no-files-found: ignore
          path: artifacts/
