name: Windows Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Install Go dependencies
        run: |
          go get .

      - name: Install OpenCV
        run: |
          echo "Downloading & extracting..."
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; $ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri https://github.com/opencv/opencv/archive/4.12.0.zip -OutFile c:\opencv\opencv-4.12.0.zip
          $ProgressPreference = 'SilentlyContinue'; Expand-Archive -Path c:\opencv\opencv-4.12.0.zip -DestinationPath c:\opencv
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; $ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri https://github.com/opencv/opencv_contrib/archive/4.12.0.zip -OutFile c:\opencv\opencv_contrib-4.12.0.zip
          $ProgressPreference = 'SilentlyContinue'; Expand-Archive -Path c:\opencv\opencv_contrib-4.12.0.zip -DestinationPath c:\opencv
          cd C:\opencv\build
          $env:PATH = $env:PATH + ';C:\Program Files (x86)\CMake\bin;C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin'
          set enable_shared=OFF
          cmake C:\opencv\opencv-4.12.0 -G "MinGW Makefiles" -BC:\opencv\build -DENABLE_CXX11=ON -DOPENCV_EXTRA_MODULES_PATH=C:\opencv\opencv_contrib-4.12.0\modules -DBUILD_SHARED_LIBS=%enable_shared% -DWITH_IPP=OFF -DWITH_MSMF=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_DOCS=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_opencv_saliency=OFF -DBUILD_opencv_wechat_qrcode=ON -DCPU_DISPATCH= -DOPENCV_GENERATE_PKGCONFIG=ON -DWITH_OPENCL_D3D11_NV=OFF -DOPENCV_ALLOCATOR_STATS_COUNTER_TYPE=int64_t -Wno-dev
          mingw32-make -j$env:NUMBER_OF_PROCESSORS
          mingw32-make install_static

      - name: Verify OpenCV
        run: |
          chdir "$(go env GOPATH)\pkg\mod\gocv.io\x\gocv@v0.42.0"
          $env:PATH = 'C:\opencv\build\install\x64\mingw\bin;' + $env:PATH
          go run -tags static --ldflags '-extldflags "-static -LC:\opencv\build\install\x64\mingw\staticlib"' cmd\version\main.go

      - name: Build
        run: |
          go build -v -tags static --ldflags '-extldflags "-static -LC:\opencv\build\install\x64\mingw\staticlib"' ./...

      - name: Test
        run: |
          $env:PATH = 'C:\opencv\build\install\x64\mingw\bin;' + $env:PATH
          go test -tags static --ldflags '-extldflags "-static -LC:\opencv\build\install\x64\mingw\staticlib"' -v ./...

      - uses: actions/upload-artifact@v6
        if: ${{ success() || failure() }}
        with:
          name: artifacts
          if-no-files-found: ignore
          path: artifacts/

      - name: Install fyne packaging tool
        run: |
          go install fyne.io/tools/cmd/fyne@latest

      - name: Package
        run: |
          fyne package -os windows -release
          ls

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            cleancredits-windows.zip